# Generated by Django 4.2.1 on 2023-05-09 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_mymodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mymodel',
            name='name',
        ),
        migrations.AddField(
            model_name='mymodel',
            name='arff',
            field=models.CharField(default='', max_length=100),
        ),
    ]
