# Generated by Django 4.2.1 on 2023-05-14 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_mymodel_name_mymodel_arff'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='accuracy',
            field=models.CharField(default='', max_length=100),
        ),
    ]
